server:
  ssl:
    enabled: true
    # key-store.properties로 설정값을 별도로 관리 할 수 있음
#    key-store: classpath:keystore.properties
#    key-password:
#    key-alias: keycert
#    key-store-type: PEMCFG.MOD
    
    # crt, key파일을 직접 매핑해서 사용할 수 있음
    certificate: classpath:tls.crt
    certificate-private-key: classpath:tls.key

  http2:
    enabled: true
