apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-test-deployment
  labels:
    app.kubernetes.io/name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring
    spec:
      containers:
        - name: http2-test
          # 로컬에서 빌드한 이미지를 작성하면 된다.
          image: http2-test:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: spring-port
          # 인증서 파일을 매핑하는 환경변수
          env:
            - name: SERVER_SSL_CERTIFICATE
              value: /etc/secret-volume/tls.crt
            - name: SERVER_SSL_CERTIFICATE-PRIVATE-KEY
              value: /etc/secret-volume/tls.key
          # secrets에 있는 인증서를 특정 디렉토리에 마운트
          volumeMounts:
            - name: tls-secret-volume
              mountPath: /etc/secret-volume
      # secrets에 있는 인증서를 특정 디렉토리에 마운트하기 위해 볼륨 설정
      volumes:
        - name: tls-secret-volume
          secret:
            # cert-manager에 인증서 설정하면서 생긴 secrets명
            secretName: selfsigned-cert-tls