apiVersion: v1
kind: Service
metadata:
  name: http2-test-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: spring-port
      name: http2-test-port